// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ParkApi.Data;

#nullable disable

namespace ParkApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231115200127_create-second-connection")]
    partial class createsecondconnection
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ParkApi.Data.FeaturesList", b =>
                {
                    b.Property<int>("FeaturesListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FeaturesListId"));

                    b.Property<bool?>("Entertainment")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Food")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Gym")
                        .HasColumnType("boolean");

                    b.Property<bool?>("PetsAllowed")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Shops")
                        .HasColumnType("boolean");

                    b.Property<bool?>("WiFi")
                        .HasColumnType("boolean");

                    b.HasKey("FeaturesListId");

                    b.ToTable("featuresLists");
                });

            modelBuilder.Entity("ParkApi.Data.LocationDetail", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LocationId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Coodinates")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LocationId");

                    b.ToTable("locationDetails");
                });

            modelBuilder.Entity("ParkApi.Data.Parks", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ParkId"));

                    b.Property<int>("FeaturesIDFeaturesListId")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LocationId")
                        .HasColumnType("integer");

                    b.Property<string>("ParkDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ParkName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ParkId");

                    b.HasIndex("FeaturesIDFeaturesListId");

                    b.HasIndex("LocationId");

                    b.ToTable("parks");
                });

            modelBuilder.Entity("ParkApi.Data.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ParkApi.Data.Parks", b =>
                {
                    b.HasOne("ParkApi.Data.FeaturesList", "FeaturesID")
                        .WithMany()
                        .HasForeignKey("FeaturesIDFeaturesListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ParkApi.Data.LocationDetail", "LocationID")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FeaturesID");

                    b.Navigation("LocationID");
                });
#pragma warning restore 612, 618
        }
    }
}
